/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CollectionRouteImport } from './routes/collection'
import { Route as MethodsRouteImport } from './routes/methods'
import { Route as VerifyRouteImport } from './routes/verify'
import { Route as WhitepaperRouteImport } from './routes/whitepaper'
import { Route as PacketsPacketIdRouteImport } from './routes/packets.$packetId'
import { Route as PacketsPacketIdIndexRouteImport } from './routes/packets.$packetId.index'
import { Route as PacketsPacketIdClaimRouteImport } from './routes/packets.$packetId.claim'
import { Route as PacketsPacketIdHistoryRouteImport } from './routes/packets.$packetId.history'
import { Route as PacketsPacketIdReceiptRouteImport } from './routes/packets.$packetId.receipt'
import { Route as PacketsPacketIdReviewRouteImport } from './routes/packets.$packetId.review'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CollectionRoute = CollectionRouteImport.update({
  id: '/collection',
  path: '/collection',
  getParentRoute: () => rootRouteImport,
} as any)
const MethodsRoute = MethodsRouteImport.update({
  id: '/methods',
  path: '/methods',
  getParentRoute: () => rootRouteImport,
} as any)
const VerifyRoute = VerifyRouteImport.update({
  id: '/verify',
  path: '/verify',
  getParentRoute: () => rootRouteImport,
} as any)
const WhitepaperRoute = WhitepaperRouteImport.update({
  id: '/whitepaper',
  path: '/whitepaper',
  getParentRoute: () => rootRouteImport,
} as any)
const PacketsPacketIdRoute = PacketsPacketIdRouteImport.update({
  id: '/packets/$packetId',
  path: '/packets/$packetId',
  getParentRoute: () => rootRouteImport,
} as any)
const PacketsPacketIdIndexRoute = PacketsPacketIdIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PacketsPacketIdRoute,
} as any)
const PacketsPacketIdClaimRoute = PacketsPacketIdClaimRouteImport.update({
  id: '/claim',
  path: '/claim',
  getParentRoute: () => PacketsPacketIdRoute,
} as any)
const PacketsPacketIdHistoryRoute = PacketsPacketIdHistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => PacketsPacketIdRoute,
} as any)
const PacketsPacketIdReceiptRoute = PacketsPacketIdReceiptRouteImport.update({
  id: '/receipt',
  path: '/receipt',
  getParentRoute: () => PacketsPacketIdRoute,
} as any)
const PacketsPacketIdReviewRoute = PacketsPacketIdReviewRouteImport.update({
  id: '/review',
  path: '/review',
  getParentRoute: () => PacketsPacketIdRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/collection': typeof CollectionRoute
  '/methods': typeof MethodsRoute
  '/verify': typeof VerifyRoute
  '/whitepaper': typeof WhitepaperRoute
  '/packets/$packetId': typeof PacketsPacketIdRouteWithChildren
  '/packets/$packetId/claim': typeof PacketsPacketIdClaimRoute
  '/packets/$packetId/history': typeof PacketsPacketIdHistoryRoute
  '/packets/$packetId/receipt': typeof PacketsPacketIdReceiptRoute
  '/packets/$packetId/review': typeof PacketsPacketIdReviewRoute
  '/packets/$packetId/': typeof PacketsPacketIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/collection': typeof CollectionRoute
  '/methods': typeof MethodsRoute
  '/verify': typeof VerifyRoute
  '/whitepaper': typeof WhitepaperRoute
  '/packets/$packetId/claim': typeof PacketsPacketIdClaimRoute
  '/packets/$packetId/history': typeof PacketsPacketIdHistoryRoute
  '/packets/$packetId/receipt': typeof PacketsPacketIdReceiptRoute
  '/packets/$packetId/review': typeof PacketsPacketIdReviewRoute
  '/packets/$packetId': typeof PacketsPacketIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/collection': typeof CollectionRoute
  '/methods': typeof MethodsRoute
  '/verify': typeof VerifyRoute
  '/whitepaper': typeof WhitepaperRoute
  '/packets/$packetId': typeof PacketsPacketIdRouteWithChildren
  '/packets/$packetId/claim': typeof PacketsPacketIdClaimRoute
  '/packets/$packetId/history': typeof PacketsPacketIdHistoryRoute
  '/packets/$packetId/receipt': typeof PacketsPacketIdReceiptRoute
  '/packets/$packetId/review': typeof PacketsPacketIdReviewRoute
  '/packets/$packetId/': typeof PacketsPacketIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/collection'
    | '/methods'
    | '/verify'
    | '/whitepaper'
    | '/packets/$packetId'
    | '/packets/$packetId/claim'
    | '/packets/$packetId/history'
    | '/packets/$packetId/receipt'
    | '/packets/$packetId/review'
    | '/packets/$packetId/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/collection'
    | '/methods'
    | '/verify'
    | '/whitepaper'
    | '/packets/$packetId/claim'
    | '/packets/$packetId/history'
    | '/packets/$packetId/receipt'
    | '/packets/$packetId/review'
    | '/packets/$packetId'
  id:
    | '__root__'
    | '/'
    | '/collection'
    | '/methods'
    | '/verify'
    | '/whitepaper'
    | '/packets/$packetId'
    | '/packets/$packetId/claim'
    | '/packets/$packetId/history'
    | '/packets/$packetId/receipt'
    | '/packets/$packetId/review'
    | '/packets/$packetId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CollectionRoute: typeof CollectionRoute
  MethodsRoute: typeof MethodsRoute
  VerifyRoute: typeof VerifyRoute
  WhitepaperRoute: typeof WhitepaperRoute
  PacketsPacketIdRoute: typeof PacketsPacketIdRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/collection': {
      id: '/collection'
      path: '/collection'
      fullPath: '/collection'
      preLoaderRoute: typeof CollectionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/methods': {
      id: '/methods'
      path: '/methods'
      fullPath: '/methods'
      preLoaderRoute: typeof MethodsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/verify': {
      id: '/verify'
      path: '/verify'
      fullPath: '/verify'
      preLoaderRoute: typeof VerifyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/whitepaper': {
      id: '/whitepaper'
      path: '/whitepaper'
      fullPath: '/whitepaper'
      preLoaderRoute: typeof WhitepaperRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/packets/$packetId': {
      id: '/packets/$packetId'
      path: '/packets/$packetId'
      fullPath: '/packets/$packetId'
      preLoaderRoute: typeof PacketsPacketIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/packets/$packetId/': {
      id: '/packets/$packetId/'
      path: '/'
      fullPath: '/packets/$packetId/'
      preLoaderRoute: typeof PacketsPacketIdIndexRouteImport
      parentRoute: typeof PacketsPacketIdRoute
    }
    '/packets/$packetId/claim': {
      id: '/packets/$packetId/claim'
      path: '/claim'
      fullPath: '/packets/$packetId/claim'
      preLoaderRoute: typeof PacketsPacketIdClaimRouteImport
      parentRoute: typeof PacketsPacketIdRoute
    }
    '/packets/$packetId/history': {
      id: '/packets/$packetId/history'
      path: '/history'
      fullPath: '/packets/$packetId/history'
      preLoaderRoute: typeof PacketsPacketIdHistoryRouteImport
      parentRoute: typeof PacketsPacketIdRoute
    }
    '/packets/$packetId/receipt': {
      id: '/packets/$packetId/receipt'
      path: '/receipt'
      fullPath: '/packets/$packetId/receipt'
      preLoaderRoute: typeof PacketsPacketIdReceiptRouteImport
      parentRoute: typeof PacketsPacketIdRoute
    }
    '/packets/$packetId/review': {
      id: '/packets/$packetId/review'
      path: '/review'
      fullPath: '/packets/$packetId/review'
      preLoaderRoute: typeof PacketsPacketIdReviewRouteImport
      parentRoute: typeof PacketsPacketIdRoute
    }
  }
}

interface PacketsPacketIdRouteChildren {
  PacketsPacketIdClaimRoute: typeof PacketsPacketIdClaimRoute
  PacketsPacketIdHistoryRoute: typeof PacketsPacketIdHistoryRoute
  PacketsPacketIdReceiptRoute: typeof PacketsPacketIdReceiptRoute
  PacketsPacketIdReviewRoute: typeof PacketsPacketIdReviewRoute
  PacketsPacketIdIndexRoute: typeof PacketsPacketIdIndexRoute
}

const PacketsPacketIdRouteChildren: PacketsPacketIdRouteChildren = {
  PacketsPacketIdClaimRoute: PacketsPacketIdClaimRoute,
  PacketsPacketIdHistoryRoute: PacketsPacketIdHistoryRoute,
  PacketsPacketIdReceiptRoute: PacketsPacketIdReceiptRoute,
  PacketsPacketIdReviewRoute: PacketsPacketIdReviewRoute,
  PacketsPacketIdIndexRoute: PacketsPacketIdIndexRoute,
}

const PacketsPacketIdRouteWithChildren = PacketsPacketIdRoute._addFileChildren(
  PacketsPacketIdRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CollectionRoute: CollectionRoute,
  MethodsRoute: MethodsRoute,
  VerifyRoute: VerifyRoute,
  WhitepaperRoute: WhitepaperRoute,
  PacketsPacketIdRoute: PacketsPacketIdRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
